### PR TITLE
Rewrite _objectDefaults to account for missing items, arrays and mismatching types. Fixes #2

### LINKED ISSUE #2: Cant change default object value after first init
Снимок экрана 2023-05-09 в 17 22 15

Having this error. I will look forward to fix it.

### PR DESCRIPTION
**Pull request by igolka97**
So i changed arg names to improve readability and reduce cognitive overhead. Also swapped out args in recursive call.

Now it works like:

Is default and storage value both is object? If yes — call again. If no:
Is default value exists in storage or default value has same `typeof` as storage value? If yes, miss it. If no — replace it. 

Right now trying to run tests, that why PR is in draft state. Just for to get acquainted.

### CODE REVIEW

**Comment by AlexDicy** [comment]
Sorry I've dumped a couple more changes in the PR to group them

**Comment by igolka97** [comment]
So even better!

**Comment by igolka97** [comment]
Do not forget to deploy new ver to npm, please

**Comment by AlexDicy** [comment]
~~Deploying right now~~
NPM package updated, let me know if you encounter any issues!

**Comment by AlexDicy** [comment]
NPM package updated, let me know if you encounter any issues!

**Comment by igolka97** [comment]
> NPM package updated, let me know if you encounter any issues!

Thank you very much. Sure, i am.

**Pull request merged**
